/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program_paytroll_karyawan.View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import program_paytroll_karyawan.Model.LoginModel;
import program_paytroll_karyawan.Partials.MenuItem;

/**
 *
 * @author rifki-alfariz-shidiq
 */
public class MainMenu2 extends javax.swing.JFrame {

    private LoginModel loginModel;
    private JFrame frame = this;

    /**
     * Creates new form MainMenu2
     */
    public MainMenu2(LoginModel model) {
        initComponents();
        loginModel = model;
        this.addSidebar();
        showDashboard();
        
        System.out.println(ClassLoader.getSystemResource("").getPath());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebar = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelMenu = new javax.swing.JPanel();
        content = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        main = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        sidebar.setBackground(new java.awt.Color(255, 255, 255));
        sidebar.setPreferredSize(new java.awt.Dimension(250, 0));

        Logo.setBackground(new java.awt.Color(255, 255, 255));
        Logo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/money-management (1).png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        label1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        label1.setText("PAYROLL APP");

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelMenu.setBackground(new java.awt.Color(255, 255, 255));
        panelMenu.setLayout(new javax.swing.BoxLayout(panelMenu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(panelMenu);

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1))
        );

        getContentPane().add(sidebar);

        content.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        jLabel2.setText("PT MAGNUS SEDAYA SELARAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        main.setLayout(new javax.swing.BoxLayout(main, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane2.setViewportView(main);

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE))
        );

        getContentPane().add(content);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu2(null).setVisible(true);
            }
        });
    }

    private void addSidebar() {
        ImageIcon iconHome      = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/speedometer.png"));
        ImageIcon iconLogout    = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/Logout Rounded_1.png"));
        ImageIcon iconMaster    = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/folder.png"));
        ImageIcon iconLocation = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/pin.png"));
        ImageIcon iconDepartement = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/building.png"));
        ImageIcon iconDivision = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/personal-information.png"));
        ImageIcon iconKaryawan = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/audience.png"));
        ImageIcon iconPeriode = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/icons8-date-span-32.png"));
        ImageIcon iconTransaksi = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/icons8-cog-32.png"));
        ImageIcon iconAbsensi = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/schedule.png"));
        ImageIcon iconLembur = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/back-in-time.png"));
        ImageIcon iconReimburse = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/money.png"));
        ImageIcon iconReport = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/icons8-reports-32.png"));
        ImageIcon iconTax = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/icons8-tax-32.png")); 
        ImageIcon iconInsurance = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/icons8-insurance-32.png")); 
        ImageIcon iconInsuranceEmploye = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/icons8-medical-insurance-32.png")); 
        
        ImageIcon iconGaji = new ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/icons8-online-payment-32.png")); 
        
        

        MenuItem menuHome = new MenuItem(iconHome, false, null, "Home", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                showDashboard();
            }
        });
        MenuItem menuLogout = new MenuItem(iconLogout, false, null, "Logout", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // TODO add your handling code here:
                frame.setVisible(false);
                new Form_Login().setVisible(true);
            }
        });

        MenuItem menuLocation = new MenuItem(null, true, iconLocation, "Location", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new LocationForm(loginModel));
                main.repaint();
                main.revalidate();
            }
        });

        MenuItem menuDepartement = new MenuItem(null, true, iconDepartement, "Departement", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new DepartementForm(loginModel));
                main.repaint();
                main.revalidate();
            }
        });

        MenuItem menuKaryawan = new MenuItem(null, true, iconKaryawan, "Karyawan", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new KaryawanForm(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        MenuItem menuDivison = new MenuItem(null, true, iconDivision, "Division", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new DivisionForm(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        MenuItem menuPeriode = new MenuItem(null, true, iconPeriode, "Periode", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new PeriodeForm(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        MenuItem menuTax = new MenuItem(null, true, iconTax, "Pajak", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Pajak");    
                main.removeAll();
                main.add(new PajakForm(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        MenuItem menuAbsensi = new MenuItem(null, true, iconAbsensi, "Daftar Absensi", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new ListAbsensi(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        MenuItem menuLembur = new MenuItem(null, true, iconLembur, "Lembur", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new lemburForm(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        MenuItem menuReimburse = new MenuItem(null, true, iconReimburse, "Reimburse", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new ReimburseForm(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        MenuItem menuLaporanAbsen = new MenuItem(null, false, null, "Laporan Absen", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new reportAbsensi(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        MenuItem menuLaporanLembur = new MenuItem(null, false, null, "Laporan Lembur", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new reportLembur(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        MenuItem menuLaporanKaryawan = new MenuItem(null, false, null, "Laporan Karyawan", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new reportKaryawan(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        MenuItem menuLaporanGajiKaryawan = new MenuItem(null, false, null, "Laporan Gaji Karyawan", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new slipGaji(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        MenuItem menuInsurance = new MenuItem(null, true, iconInsurance, "Asuransi", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new InsuranceForm(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        MenuItem menuInsuranceEmploye = new MenuItem(null, true, iconInsuranceEmploye, "Asuransi Karyawan", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new EmployeInsuranceForm(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        MenuItem menuGaji = new MenuItem(null, true, iconGaji, "Gaji", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new GajiForm(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        
        MenuItem menuLaporanDetailGaji = new MenuItem(null, false, null, "Laporan Detail Gaji", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new detailGaji(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        
        MenuItem menuLaporanPembayaran = new MenuItem(null, false, null, "Laporan Pembayaran", new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                main.removeAll();
                main.add(new reportPembayaran(loginModel));
                main.repaint();
                main.revalidate();
            }
        });
        
        MenuItem menuMaster = new MenuItem(iconMaster, false, null, "Master", null, menuLocation, menuDepartement, menuDivison, menuKaryawan, menuPeriode,menuTax,menuInsurance, menuInsuranceEmploye);

        MenuItem menuTransaksi = new MenuItem(iconTransaksi, false, null, "Transaksi", null, menuAbsensi, menuLembur, menuReimburse, menuGaji);
        
        MenuItem menuLaporan = new MenuItem(iconReport, false, null, "Report", null, menuLaporanAbsen,menuLaporanLembur,menuLaporanKaryawan,menuLaporanGajiKaryawan,menuLaporanDetailGaji,menuLaporanPembayaran);
        addMenu(menuHome, menuMaster, menuTransaksi, menuLaporan);

        addMenu(menuLogout);
    }

    private void addMenu(MenuItem... menu) {
        for (int i = 0; i < menu.length; i++) {
            panelMenu.add(menu[i]);
            ArrayList<MenuItem> subMenu = menu[i].getSubMenu();
            for (MenuItem m : subMenu) {
                addMenu(m);
            }
        }
        panelMenu.revalidate();
    }


    private void showDashboard(){
        main.removeAll();
        main.add(new ViewDashboard(loginModel));
        main.repaint();
        main.revalidate();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Logo;
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private javax.swing.JPanel main;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
