/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package program_paytroll_karyawan.View;

import javax.swing.JFrame;
import program_paytroll_karyawan.Model.LoginModel;

/**
 *
 * @author rifki-alfariz-shidiq
 */
public class MainMenu extends javax.swing.JFrame {

    private LoginModel loginModel;
    /**
     * Creates new form MainMenu
     */
    public MainMenu(LoginModel model) {
        initComponents();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        loginModel = model;
        initComponents();
        pnUtama.removeAll();
        pnUtama.add(new ViewDashboard(loginModel));
        pnUtama.repaint();
        pnUtama.revalidate();
        
        removeAllNav();
        validateAccess();
    }
    
    public void removeAllNav(){
        navLocation.setVisible(false);
        navDepartement.setVisible(false);
        navDivision.setVisible(false);
        navKaryawan.setVisible(false);
        navDaftarAbsensi.setVisible(false);
        navLembur.setVisible(false);
        navReimburse.setVisible(false);
        
        btnReportAbsensi.setVisible(false);
        btnReportDataKaryawan.setVisible(false);
        btnReportLembur.setVisible(false);
        btnSlipGaji.setVisible(false);
        jLabel13.setVisible(false);
        
        
    }
    
    public void validateAccess(){
        String role = loginModel.getRole();
//        role = role.isEmpty("") ? "admin" : role;
        role = (role == null || role.equals("")) ? "admin" : role;
        if(role.equals("admin")){
            navLocation.setVisible(true);
            navDepartement.setVisible(true);
            navDivision.setVisible(true);
            navKaryawan.setVisible(true);
            navDaftarAbsensi.setVisible(true);
            navLembur.setVisible(true);
            navReimburse.setVisible(true);

            jLabel13.setVisible(true);
            btnReportAbsensi.setVisible(true);
            btnReportDataKaryawan.setVisible(true);
            btnReportLembur.setVisible(true);
            btnSlipGaji.setVisible(true);
        } 
        
        if(role.equals("user")){
           navDaftarAbsensi.setVisible(true);
            navLembur.setVisible(true);
            navReimburse.setVisible(true); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnKiri = new javax.swing.JPanel();
        pnKiriAtas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnKiriBawah = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        baseScrollPane = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        navHome = new javax.swing.JButton();
        navLocation = new javax.swing.JButton();
        navDepartement = new javax.swing.JButton();
        navDivision = new javax.swing.JButton();
        navKaryawan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        navDaftarAbsensi = new javax.swing.JButton();
        navLembur = new javax.swing.JButton();
        navReimburse = new javax.swing.JButton();
        btnSlipGaji = new javax.swing.JButton();
        btnReportDataKaryawan = new javax.swing.JButton();
        btnReportLembur = new javax.swing.JButton();
        btnReportAbsensi = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        navPeriode = new javax.swing.JButton();
        pnKanan = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        pnUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnKiri.setBackground(new java.awt.Color(255, 255, 255));

        pnKiriAtas.setBackground(new java.awt.Color(255, 255, 255));
        pnKiriAtas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/money-management (1).png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel7.setText("EMPLOYEE");

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel6.setText("APPLICATION");

        javax.swing.GroupLayout pnKiriAtasLayout = new javax.swing.GroupLayout(pnKiriAtas);
        pnKiriAtas.setLayout(pnKiriAtasLayout);
        pnKiriAtasLayout.setHorizontalGroup(
            pnKiriAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKiriAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnKiriAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        pnKiriAtasLayout.setVerticalGroup(
            pnKiriAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKiriAtasLayout.createSequentialGroup()
                .addGroup(pnKiriAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKiriAtasLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(pnKiriAtasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnKiriBawah.setBackground(new java.awt.Color(255, 255, 255));
        pnKiriBawah.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 0, 0, 0, new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 153));
        jLabel5.setText("Payroll Application 1.0");

        javax.swing.GroupLayout pnKiriBawahLayout = new javax.swing.GroupLayout(pnKiriBawah);
        pnKiriBawah.setLayout(pnKiriBawahLayout);
        pnKiriBawahLayout.setHorizontalGroup(
            pnKiriBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnKiriBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnKiriBawahLayout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jLabel5)
                    .addContainerGap(63, Short.MAX_VALUE)))
        );
        pnKiriBawahLayout.setVerticalGroup(
            pnKiriBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
            .addGroup(pnKiriBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnKiriBawahLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jLabel5)
                    .addContainerGap(8, Short.MAX_VALUE)))
        );

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        baseScrollPane.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Master Data");

        navHome.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        navHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/speedometer.png"))); // NOI18N
        navHome.setText("Dashboard");
        navHome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navHome.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        navHome.setMinimumSize(new java.awt.Dimension(189, 59));
        navHome.setPreferredSize(new java.awt.Dimension(189, 59));
        navHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navHomeActionPerformed(evt);
            }
        });

        navLocation.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        navLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/pin.png"))); // NOI18N
        navLocation.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navLocation.setLabel("Location");
        navLocation.setMinimumSize(new java.awt.Dimension(189, 59));
        navLocation.setPreferredSize(new java.awt.Dimension(189, 59));
        navLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navLocationActionPerformed(evt);
            }
        });

        navDepartement.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        navDepartement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/building.png"))); // NOI18N
        navDepartement.setText("Departement");
        navDepartement.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navDepartement.setMinimumSize(new java.awt.Dimension(189, 59));
        navDepartement.setPreferredSize(new java.awt.Dimension(189, 59));
        navDepartement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navDepartementActionPerformed(evt);
            }
        });

        navDivision.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        navDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/personal-information.png"))); // NOI18N
        navDivision.setText("Division");
        navDivision.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navDivision.setMinimumSize(new java.awt.Dimension(189, 59));
        navDivision.setPreferredSize(new java.awt.Dimension(189, 59));
        navDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navDivisionActionPerformed(evt);
            }
        });

        navKaryawan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        navKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/audience.png"))); // NOI18N
        navKaryawan.setText("Karyawan");
        navKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navKaryawan.setMinimumSize(new java.awt.Dimension(189, 59));
        navKaryawan.setPreferredSize(new java.awt.Dimension(189, 59));
        navKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navKaryawanActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Transaksi");

        navDaftarAbsensi.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        navDaftarAbsensi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/schedule.png"))); // NOI18N
        navDaftarAbsensi.setText("Daftar Absensi");
        navDaftarAbsensi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navDaftarAbsensi.setMinimumSize(new java.awt.Dimension(189, 59));
        navDaftarAbsensi.setPreferredSize(new java.awt.Dimension(189, 59));
        navDaftarAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navDaftarAbsensiActionPerformed(evt);
            }
        });

        navLembur.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        navLembur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/back-in-time.png"))); // NOI18N
        navLembur.setText("Lembur");
        navLembur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navLembur.setMinimumSize(new java.awt.Dimension(189, 59));
        navLembur.setPreferredSize(new java.awt.Dimension(189, 59));
        navLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navLemburActionPerformed(evt);
            }
        });

        navReimburse.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        navReimburse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/money.png"))); // NOI18N
        navReimburse.setText("Reimburse");
        navReimburse.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navReimburse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navReimburseActionPerformed(evt);
            }
        });

        btnSlipGaji.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnSlipGaji.setText("Laporan Gaji Karyawan");
        btnSlipGaji.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSlipGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSlipGajiActionPerformed(evt);
            }
        });

        btnReportDataKaryawan.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnReportDataKaryawan.setText("Laporan Data Karyawan");
        btnReportDataKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportDataKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportDataKaryawanActionPerformed(evt);
            }
        });

        btnReportLembur.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnReportLembur.setText("Laporan Lembur");
        btnReportLembur.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportLembur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportLemburActionPerformed(evt);
            }
        });

        btnReportAbsensi.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        btnReportAbsensi.setText("Laporan Absensi");
        btnReportAbsensi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReportAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportAbsensiActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 21)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("Report");

        navPeriode.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        navPeriode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/audience.png"))); // NOI18N
        navPeriode.setText("Periode");
        navPeriode.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        navPeriode.setMinimumSize(new java.awt.Dimension(189, 59));
        navPeriode.setPreferredSize(new java.awt.Dimension(189, 59));
        navPeriode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navPeriodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout baseScrollPaneLayout = new javax.swing.GroupLayout(baseScrollPane);
        baseScrollPane.setLayout(baseScrollPaneLayout);
        baseScrollPaneLayout.setHorizontalGroup(
            baseScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseScrollPaneLayout.createSequentialGroup()
                .addGroup(baseScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseScrollPaneLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(baseScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnReportDataKaryawan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(btnReportLembur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReportAbsensi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navDaftarAbsensi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navLembur, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navReimburse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSlipGaji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(baseScrollPaneLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(baseScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(navPeriode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navLocation, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(navDepartement, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navDivision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navKaryawan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(10, Short.MAX_VALUE))
            .addGroup(baseScrollPaneLayout.createSequentialGroup()
                .addGroup(baseScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        baseScrollPaneLayout.setVerticalGroup(
            baseScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseScrollPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(navHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(navDepartement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(navDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(navKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(navPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navDaftarAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(navLembur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(navReimburse, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(0, 0, 0)
                .addComponent(btnReportAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReportLembur, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnReportDataKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnSlipGaji, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(baseScrollPane);

        javax.swing.GroupLayout pnKiriLayout = new javax.swing.GroupLayout(pnKiri);
        pnKiri.setLayout(pnKiriLayout);
        pnKiriLayout.setHorizontalGroup(
            pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKiriLayout.createSequentialGroup()
                .addGroup(pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnKiriBawah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnKiriAtas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnKiriLayout.setVerticalGroup(
            pnKiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKiriLayout.createSequentialGroup()
                .addComponent(pnKiriAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(pnKiriBawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnKanan.setBackground(new java.awt.Color(255, 255, 255));
        pnKanan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(0, 0, 0)));

        jPanel2.setBackground(new java.awt.Color(0, 102, 153));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 64)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PT MAGNUS SEDAYA SELARAS");

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/Logout Rounded_1.png"))); // NOI18N
        jButton6.setText("Logout");
        jButton6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(823, 823, 823)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton6)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addGap(0, 0, 0))
        );

        pnUtama.setBackground(new java.awt.Color(255, 255, 255));
        pnUtama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnKananLayout = new javax.swing.GroupLayout(pnKanan);
        pnKanan.setLayout(pnKananLayout);
        pnKananLayout.setHorizontalGroup(
            pnKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnKananLayout.setVerticalGroup(
            pnKananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKananLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnKiri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnKiri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnKanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void navHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navHomeActionPerformed
        // TODO add your handling code here:
        
        pnUtama.removeAll();
        pnUtama.add(new ViewDashboard(loginModel));
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_navHomeActionPerformed

    private void navLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navLocationActionPerformed
        // TODO add your handling code here:
        pnUtama.removeAll();
        pnUtama.add(new LocationForm(loginModel));
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_navLocationActionPerformed

    private void navDepartementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navDepartementActionPerformed
        // TODO add your handling code here:
        pnUtama.removeAll();
        pnUtama.add(new DepartementForm(loginModel));
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_navDepartementActionPerformed

    private void navDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navDivisionActionPerformed
        // TODO add your handling code here:
        pnUtama.removeAll();
        pnUtama.add(new DivisionForm(loginModel));
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_navDivisionActionPerformed

    private void navKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navKaryawanActionPerformed
        // TODO add your handling code here:
        pnUtama.removeAll();
        pnUtama.add(new KaryawanForm(loginModel));
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_navKaryawanActionPerformed

    private void navDaftarAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navDaftarAbsensiActionPerformed
        // TODO add your handling code here:
        pnUtama.removeAll();
        pnUtama.add(new ListAbsensi(loginModel));
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_navDaftarAbsensiActionPerformed

    private void navLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navLemburActionPerformed
        // TODO add your handling code here:
        pnUtama.removeAll();
        pnUtama.add(new lemburForm(loginModel));
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_navLemburActionPerformed

    private void navReimburseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navReimburseActionPerformed
        // TODO add your handling code here:
        pnUtama.removeAll();
        pnUtama.add(new ReimburseForm(loginModel));
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_navReimburseActionPerformed

    private void btnSlipGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSlipGajiActionPerformed
        // TODO add your handling code here:
        pnUtama.removeAll();
        pnUtama.add(new slipGaji(loginModel));
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btnSlipGajiActionPerformed

    private void btnReportDataKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportDataKaryawanActionPerformed
        // TODO add your handling code here:
        pnUtama.removeAll();
        pnUtama.add(new reportKaryawan(loginModel));
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btnReportDataKaryawanActionPerformed

    private void btnReportLemburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportLemburActionPerformed
        // TODO add your handling code here:
        pnUtama.removeAll();
        pnUtama.add(new reportLembur(loginModel));
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btnReportLemburActionPerformed

    private void btnReportAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportAbsensiActionPerformed
        // TODO add your handling code here:
        pnUtama.removeAll();
        pnUtama.add(new reportAbsensi(loginModel));
        pnUtama.repaint();
        pnUtama.revalidate();
    }//GEN-LAST:event_btnReportAbsensiActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new Form_Login().setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void navPeriodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navPeriodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navPeriodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu(new LoginModel()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel baseScrollPane;
    private javax.swing.JButton btnReportAbsensi;
    private javax.swing.JButton btnReportDataKaryawan;
    private javax.swing.JButton btnReportLembur;
    private javax.swing.JButton btnSlipGaji;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton navDaftarAbsensi;
    private javax.swing.JButton navDepartement;
    private javax.swing.JButton navDivision;
    private javax.swing.JButton navHome;
    private javax.swing.JButton navKaryawan;
    private javax.swing.JButton navLembur;
    private javax.swing.JButton navLocation;
    private javax.swing.JButton navPeriode;
    private javax.swing.JButton navReimburse;
    private javax.swing.JPanel pnKanan;
    private javax.swing.JPanel pnKiri;
    private javax.swing.JPanel pnKiriAtas;
    private javax.swing.JPanel pnKiriBawah;
    private javax.swing.JPanel pnUtama;
    // End of variables declaration//GEN-END:variables
}
