/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program_paytroll_karyawan.View;

import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import program_paytroll_karyawan.Config.DbConnection;

/**
 *
 * @author mymau
 */
public class reportReimburse extends javax.swing.JPanel {

    private DefaultTableModel tableReimburse;
    /**
     * Creates new form reportReimburse
     */
    public reportReimburse() {
        initComponents();
        initTable();
    }

    public String getMonthName(int id){
        String month = "";
        if(id==0){
            month = "January";
        }else if(id==1){
            month = "February";
        }else if(id==2){
            month = "March";
        }else if(id==3){
            month = "April";
        }else if(id==4){
            month = "May";
        }else if(id==5){
            month = "June";
        }else if(id==6){
            month = "July";
        }else if(id==7){
            month = "August";
        }else if(id==8){
            month = "September";
        }else if(id==9){
            month = "October";
        }else if(id==10){
            month = "November";
        }else{
            month = "December";
        }
        return month;
    }
    
    private void initTable() {
        tableReimburse = new DefaultTableModel();
        tableReimburse.addColumn("NO");
        tableReimburse.addColumn("Periode");
        tableReimburse.addColumn("Nama Karyawan");
        tableReimburse.addColumn("No Reimbursment");
        tableReimburse.addColumn("Total");
        jTableReimburse.setModel(tableReimburse);
    }
     
    private void showData() {
        System.out.println(getMonthName(jMonthBulan.getMonth()));
        try {
            String sql = "SELECT e.employe_name AS employe_name,"
                    + " MONTHNAME(r.created_at) AS nameMonth,"
                    + " a.employe_id AS employe_id, "
                    + "COUNT(l.lembur_id) AS total_lembur, "
                    + "(COUNT(l.lembur_id) * 200000) AS biaya_lembur FROM "
                    + "lembur l LEFT JOIN absensi a ON l.absensi_id = a.absensi_id "
                    + "LEFT JOIN employe e ON a.employe_id = e.employe_id "
                    + "WHERE monthname(a.absensi_date) = '" + getMonthName(jMonthBulan.getMonth())+"' "
                    + "GROUP BY nameMonth,employe_id";
            PreparedStatement statement = DbConnection.getConnection().prepareStatement(sql);
            ResultSet resultSet = statement.executeQuery();
            int no = 1;
            while (resultSet.next()) {
                int nomor = no;
                no++;
                String namaKaryawan = resultSet.getString("employe_name");
                String periode = resultSet.getString("nameMonth");
                String noReimburse = resultSet.getString("total_lembur");
                int bayar = resultSet.getInt("biaya_lembur");
                
                Object[] row = new Object[]{nomor, periode,  namaKaryawan, noReimburse, bayar};
                tableReimburse.addRow(row);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menampilkan data!", "Error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();}
    }
    
    private void clearData() {
        tableReimburse.setRowCount(0);
        jMonthBulan.getMonth();
    }
    
    private void printReport() {
        try {
            HashMap<String, Object> parameters = new HashMap<>();
            parameters.put("TglStart", jMonthBulan.getMonth());
            
            File file = new File("src/Report/laporanReimburse.jasper");
            JasperReport jr = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameters, DbConnection.getConnection());
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanelReim = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMonthBulan = new com.toedter.calendar.JMonthChooser();
        btnShow = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReimburse = new javax.swing.JTable();

        setLayout(new java.awt.CardLayout());

        cardPanelReim.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Report > Reimburse");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/schedule.png"))); // NOI18N

        btnShow.setText("Show");

        btnCancel.setText("Cancel");

        btnPrint.setText("Print");

        jTableReimburse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableReimburse);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jMonthBulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrint)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnShow, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jMonthBulan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(20, 20, 20))
        );

        cardPanelReim.add(jPanel1, "card2");

        add(cardPanelReim, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnShow;
    private javax.swing.JPanel cardPanelReim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private com.toedter.calendar.JMonthChooser jMonthBulan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReimburse;
    // End of variables declaration//GEN-END:variables
}
