/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package program_paytroll_karyawan.View;

import java.text.SimpleDateFormat;
import java.util.Timer;
import java.util.TimerTask;
import program_paytroll_karyawan.Dao.AbsensiDAO;
import program_paytroll_karyawan.Dao.KaryawanDAO;
import program_paytroll_karyawan.Model.LoginModel;

/**
 *
 * @author lincbp
 */
public class ViewDashboard extends javax.swing.JPanel {
    private LoginModel loginModel;

    /**
     * Creates new form ViewDashboard
     */
    public ViewDashboard(LoginModel loginModel) {
        initComponents();
        String displayName = loginModel.getEmploye_name()+" - "+loginModel.getRole();
        namaTxt.setText(displayName);
        nikTxt.setText(loginModel.getNik());
        
        pnAbsen.add(new AbsenPanel(loginModel));
        pnAbsen.repaint();
        pnAbsen.revalidate();
        
        getTime();
        
        System.out.println();
        
        AbsensiDAO absensiController = new AbsensiDAO();
        int totalAbsen = absensiController.getTotalAbsenByMonth(Integer.parseInt(new SimpleDateFormat("MM").format(new java.util.Date())),loginModel.getEmploye_id());
            totalAbsenTxt.setText(String.valueOf(totalAbsen));
        
        // Show Total Karyawan
        if(loginModel.getRole().equals("admin")){
            pnTotalEmploye.setVisible(true);
            KaryawanDAO karyawanController = new KaryawanDAO();
            int a = karyawanController.getTotalEmploye();
            totalKaryawanTxt.setText(String.valueOf(a));
        }else{
            pnTotalEmploye.setVisible(false);
        }
    }
    public void getTime(){
        Timer t2 = new Timer();
        t2.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                timeTxt.setText(new SimpleDateFormat("dd-MM-yyyy hh:mm:ss").format(new java.util.Date()));
            }
        },0,1000);
    }
    
    public void initAbsen(){
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        namaTxt = new javax.swing.JLabel();
        nikTxt = new javax.swing.JLabel();
        timeTxt = new javax.swing.JLabel();
        pnAbsen = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnTotalEmploye = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        totalKaryawanTxt = new javax.swing.JLabel();
        pnTotalEmploye1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        totalAbsenTxt = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELAMAT DATANG");

        namaTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namaTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        namaTxt.setText("jLabel2");

        nikTxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nikTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nikTxt.setText("jLabel2");

        timeTxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        timeTxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeTxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/Clock.png"))); // NOI18N
        timeTxt.setText("jLabel2");
        timeTxt.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        pnAbsen.setBackground(new java.awt.Color(255, 102, 102));
        pnAbsen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnAbsen.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Master Data > Dashboard");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/program_paytroll_karyawan/Assets/Icons/speedometer.png"))); // NOI18N

        pnTotalEmploye.setBackground(new java.awt.Color(255, 255, 255));
        pnTotalEmploye.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnTotalEmploye.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Total Karyawan");
        jLabel4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnTotalEmploye.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        totalKaryawanTxt.setBackground(new java.awt.Color(255, 255, 255));
        totalKaryawanTxt.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        totalKaryawanTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalKaryawanTxt.setText("jLabel5");
        totalKaryawanTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnTotalEmploye.add(totalKaryawanTxt, java.awt.BorderLayout.CENTER);

        pnTotalEmploye1.setBackground(new java.awt.Color(255, 255, 255));
        pnTotalEmploye1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnTotalEmploye1.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Total Absen");
        jLabel5.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnTotalEmploye1.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        totalAbsenTxt.setBackground(new java.awt.Color(255, 255, 255));
        totalAbsenTxt.setFont(new java.awt.Font("Liberation Sans", 1, 48)); // NOI18N
        totalAbsenTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAbsenTxt.setText("jLabel5");
        totalAbsenTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnTotalEmploye1.add(totalAbsenTxt, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(namaTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nikTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pnAbsen, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnTotalEmploye, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnTotalEmploye1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addComponent(timeTxt)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nikTxt)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnAbsen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnTotalEmploye1, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                    .addComponent(pnTotalEmploye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel namaTxt;
    private javax.swing.JLabel nikTxt;
    private javax.swing.JPanel pnAbsen;
    private javax.swing.JPanel pnTotalEmploye;
    private javax.swing.JPanel pnTotalEmploye1;
    private javax.swing.JLabel timeTxt;
    private javax.swing.JLabel totalAbsenTxt;
    private javax.swing.JLabel totalKaryawanTxt;
    // End of variables declaration//GEN-END:variables
}
